gateway_url: "http://gateway.kube-system.svc.cluster.local:80"
poll_interval: 60
namespace: "production"
timeout_seconds: 600
max_concurrency: 10
services_dir: "services"
dialog_timeout: 300
trigger_keyword: "/deploy"
cancel_keyword: "/cancel"
invalid_responses:
  - "Please use /deploy to start a deployment."
  - "Invalid command. Try /deploy."
  - "Use /deploy to initiate a deployment process."
telegram_bots:
  api-service: "your-bot-token"
  web-service: "your-bot-token"
telegram_chats:
  api-service: 123456789
  web-service: 987654321
service_keywords:
  api-service: "api-service"
  web-service: "web-service"
environments:
  - prod
  - staging
  - dev