trigger_keyword:
  - "deploy"
  - "发布"
  - "update"
  - "upgrade"
cancel_keyword:
  - "cancel"
  - "取消"
  - "停止"
  - "tingzhi"
  - "quxiao"
invalid_responses:
  - "请使用触发关键字（如 deploy、发布、update、upgrade）开始部署。\nPlease use a trigger keyword (e.g., deploy, 发布, update, upgrade) to start a deployment."
  - "无效命令。请尝试触发关键字。\nInvalid command. Try a trigger keyword."
  - "使用触发关键字（如 deploy、发布、update、upgrade）开始部署流程。\nUse a trigger keyword (e.g., deploy, 发布, update, upgrade) to initiate a deployment process."