gateway_url: "http://18.13.24.10:8081"
gateway_listen_addr: "0.0.0.0:8099"
allowed_ips:
  - "10.1.0.0/16"
  - "10.1.2.3/32"
  - "10.1.2.5"
poll_interval: 60
namespace: "international"
timeout_seconds: 600
max_concurrency: 10
services_dir: "services"
dialog_timeout: 300
trigger_keyword:
  - "deploy"
  - "发布"
  - "update"
  - "upgrade"
cancel_keyword:
  - "cancel"
  - "取消"
  - "停止"
  - "tingzhi"
  - "quxiao"
telegram_bots:
  api-service: "YOUR_BOT_TOKEN"
  web-service: "YOUR_BOT_TOKEN"
telegram_chats:
  api-service: -482wewew05
  web-service: -4829719305
service_keywords:
  api-service: "international"
  web-service: "gaming"
environments:
  eks-test: "international"
  eks-pre: "pre"