gateway_url: "http://18.23.22.120:8080/"
poll_interval: 60
namespace: "international"
timeout_seconds: 600
max_concurrency: 10
services_dir: "services"
dialog_timeout: 300
trigger_keyword: "deploy"
cancel_keyword: "cancel"
invalid_responses:
  - "Please use /deploy to start a deployment."
  - "Invalid command. Try /deploy."
  - "Use /deploy to initiate a deployment process."
telegram_bots:
  api-service: "821232323230:AAFoOquduX23hRKgazt323Y2323YM8hI"
  web-service: "2323232323223:AAH2n8A0C6Ijq6-3232332323232323"
telegram_chats:
  api-service: -482wewew05
  web-service: -4829dsds71
service_keywords:
  api-service: "international"
  web-service: "gaming"
environments:
  - eks-test
  - eks
  - eks-us