# API配置
api:
  base_url: "http://api.example.com"
  push_interval: 5s
  max_retries: 0  # 无限重试

# K8s配置
kubernetes:
  auth_type: "kubeconfig"
  kubeconfig: "~/.kube/config"
  namespace: "default"

# 部署配置
deploy:
  wait_timeout: 5m        # 等待新版本就绪超时
  rollback_timeout: 3m    # 回滚等待超时
  poll_interval: 5s       # 健康检查轮询间隔

# Redis配置
redis:
  addr: "localhost:6379"
  db: 0
  ttl: 24h
  max_retries: 3

# 任务队列配置
task:
  queue_workers: 5
  poll_interval_seconds: 30
  max_retries: 3
  retry_delay_seconds: 30
  max_queue_size: 100

# Telegram配置
telegram:
  bots:
    - name: "prod-bot"
      token: "${TELEGRAM_TOKEN}"
      group_id: "${TELEGRAM_GROUP_ID}"
      services:
        "API": ["API-GATEWAY"]
        "USER": ["USER-SERVICE"]
      enabled: true

log_level: "info"